"use client";
import {useMemo,useState} from "react";
import {useResearcher} from "@/identity/researcher-session";
import {createStudy} from "@/contracts/study-registry";
import type {StudyDraft} from "@/research/study/study-model";
import {inspectTransaction,finalizeResearchTx,type ResearchTxState} from "@/consensus/write-pipeline";

const initial:StudyDraft={studyKey:"",title:"",field:"",claim:"",protocol:{population:"",procedure:"",measurement:"",analysis:"",window:""},outcomeRule:"",evidencePolicy:{required_kinds:["DATASET","METHOD","ANALYSIS","RESULT_TABLE"],min_distinct_origins:2,min_distinct_artifacts:4,allowed_origins:[],required_origins:[],notes:""},analysisSpec:{version:1,profile:"ONE_SAMPLE_THRESHOLD",schema_version:1,value_field:"value",scale:1000,comparator:">=",threshold_scaled:0,min_value_scaled:-1000000000000000,max_value_scaled:1000000000000000},provenancePolicy:{version:1,immutable_required:true,allowed_profiles:["GITHUB_COMMIT","ZENODO_RECORD","GENERIC_CONTENT_ADDRESS"],required_profiles:[],minimum_provenance_level:1,max_artifact_chars:48000,machine_readable_dataset:true},attemptTtlSeconds:"604800",rewardGen:"0",maxRewardedAttempts:"0"};
const steps=["claim","protocol","outcome","evidence","reward","freeze"];
const PROFILE_OPTIONS=["ONE_SAMPLE_THRESHOLD","TWO_GROUP_MEAN_DIFF","BINARY_RATE_DIFF"] as const;
const SCALES=[1,10,100,1000,10000,100000,1000000];
function analysisError(a:StudyDraft["analysisSpec"]):string{
 if(!PROFILE_OPTIONS.includes(a.profile as typeof PROFILE_OPTIONS[number]))return "Choose a supported deterministic analysis profile.";
 if(!SCALES.includes(Number(a.scale)))return "Scale must be a power of ten.";
 if(![">=",">","<=","<"].includes(String(a.comparator)))return "Choose a supported comparator.";
 if(!String(a.value_field||"").trim())return "Value field is required.";
 if(!Number.isInteger(Number(a.threshold_scaled)))return "Threshold must be an integer in the configured scale.";
 if(!Number.isInteger(Number(a.min_value_scaled))||!Number.isInteger(Number(a.max_value_scaled))||Number(a.min_value_scaled)>Number(a.max_value_scaled))return "The scaled value range is invalid.";
 if((a.profile==="TWO_GROUP_MEAN_DIFF"||a.profile==="BINARY_RATE_DIFF")&&(!String(a.group_field||"").trim()||!String(a.group_a||"").trim()||!String(a.group_b||"").trim()))return "Group field, group A, and group B are required.";
 if((a.profile==="TWO_GROUP_MEAN_DIFF"||a.profile==="BINARY_RATE_DIFF")&&a.group_a===a.group_b)return "Group A and group B must differ.";
 if(a.profile==="BINARY_RATE_DIFF"&&!String(a.success_field||"").trim())return "Success field is required.";
 return "";
}
function selectAnalysisProfile(current:StudyDraft["analysisSpec"],profile:StudyDraft["analysisSpec"]["profile"]):StudyDraft["analysisSpec"]{
 const base={version:current.version,profile,schema_version:current.schema_version,value_field:current.value_field||"value",scale:current.scale||1000,comparator:current.comparator||">=",threshold_scaled:current.threshold_scaled??0,min_value_scaled:current.min_value_scaled??-1000000000000000,max_value_scaled:current.max_value_scaled??1000000000000000};
 if(profile==="ONE_SAMPLE_THRESHOLD")return base;
 const grouped={...base,group_field:current.group_field||"group",group_a:current.group_a||"A",group_b:current.group_b||"B"};
 return profile==="BINARY_RATE_DIFF"?{...grouped,success_field:current.success_field||"success"}:grouped;
}
export function RegisterStudy({onExit,onCreated}:{onExit:()=>void;onCreated:()=>void}){
 const w=useResearcher();const[d,setD]=useState(initial),[step,setStep]=useState(0),[err,setErr]=useState(""),[tx,setTx]=useState<ResearchTxState|null>(null);const p=d.protocol;
 const canNext=useMemo(()=>step===0?d.studyKey.length>=3&&d.title.length>=6&&d.field.length>=2&&d.claim.length>=20:step===1?Object.values(p).every(v=>String(v).trim().length>0)&&!analysisError(d.analysisSpec):step===2?d.outcomeRule.length>=20:step===3?d.evidencePolicy.required_kinds.length>=2:step===4?Number(d.rewardGen)>=0&&Number(d.maxRewardedAttempts)>=0:true,[step,d,p]);
 const patchProtocol=(k:string,v:string)=>setD(x=>({...x,protocol:{...x.protocol,[k]:v}}));
 const patchAnalysis=(k:string,v:string|number)=>setD(x=>({...x,analysisSpec:{...x.analysisSpec,[k]:typeof v==="string"&&["scale","threshold_scaled","min_value_scaled","max_value_scaled"].includes(k)?Number(v):v}}));
 const changeProfile=(profile:StudyDraft["analysisSpec"]["profile"])=>setD(x=>({...x,analysisSpec:selectAnalysisProfile(x.analysisSpec,profile)}));
 const selectedKinds=(el:HTMLSelectElement)=>Array.from(el.selectedOptions).map(o=>o.value);
 const submit=async()=>{setErr("");const invalid=analysisError(d.analysisSpec);if(invalid){setErr(invalid);setStep(1);return}if(!w.address){setErr("Connect a researcher identity before freezing the study.");return}if(!w.chainOk){setErr("Switch your wallet to GenLayer Studionet 61999.");return}try{await createStudy(w.address,d,setTx)}catch(e:any){setErr(e?.message||"Study registration failed")}};
 const check=async()=>{if(!tx?.txId)return;try{const s=await inspectTransaction(w.address||undefined,tx.txId);setTx(s);if(s.phase==="FINALIZED")onCreated()}catch(e:any){setErr(e?.message||"Could not inspect registration finality")}};
 const finalize=async()=>{if(!w.address||!tx?.txId)return;try{await finalizeResearchTx(w.address,tx.txId);setTimeout(check,1200)}catch(e:any){setErr(e?.message||"Registration finalization failed")}};
 return <section className="registration-frame"><div className="registration-head"><div><div className="journal-kicker">preregistration desk</div><h2>Register a study</h2></div><button className="text-action" onClick={onExit}>return to atlas</button></div><div className="step-rail">{steps.map((s,i)=><div key={s} className={i<step?"done":i===step?"active":""}>{String(i+1).padStart(2,"0")} {s}</div>)}</div><div className="registration-sheet">{step===0&&<><h3>What claim is being tested?</h3><p>Write the claim precisely enough that another researcher can understand what the replication is meant to evaluate.</p><Field label="study key"><input value={d.studyKey} onChange={e=>setD(x=>({...x,studyKey:e.target.value.replace(/[^A-Za-z0-9_-]/g,"")}))} placeholder="sleep-recall-01"/></Field><Field label="title"><input value={d.title} onChange={e=>setD(x=>({...x,title:e.target.value}))} placeholder="Sleep duration and delayed recall"/></Field><Field label="field"><input value={d.field} onChange={e=>setD(x=>({...x,field:e.target.value}))} placeholder="Behavioural science"/></Field><Field label="registered claim"><textarea value={d.claim} onChange={e=>setD(x=>({...x,claim:e.target.value}))} placeholder="State the exact scientific claim to be tested."/></Field></>}
 {step===1&&<><h3>Freeze the method.</h3><p>The protocol and deterministic analysis become immutable once the registration transaction is finalized.</p>{(["population","procedure","measurement","analysis","window"] as const).map(k=><Field key={k} label={k}><textarea value={String(p[k])} onChange={e=>patchProtocol(k,e.target.value)} placeholder={`Describe the registered ${k}.`}/></Field>)}<div className="config-leaf"><div className="journal-kicker">frozen deterministic analysis</div><p>These fields are stored in the preregistration and cannot be changed after registration. Thresholds are integer values in the selected fixed-point scale.</p><Field label="analysis profile"><select value={d.analysisSpec.profile} onChange={e=>changeProfile(e.target.value as StudyDraft["analysisSpec"]["profile"])}>{PROFILE_OPTIONS.map(profile=><option key={profile}>{profile}</option>)}</select></Field><div className="two-fields"><Field label="scale"><select value={d.analysisSpec.scale} onChange={e=>patchAnalysis("scale",e.target.value)}>{SCALES.map(scale=><option key={scale}>{scale}</option>)}</select></Field><Field label="comparator"><select value={d.analysisSpec.comparator} onChange={e=>patchAnalysis("comparator",e.target.value)}><option>&gt;=</option><option>&gt;</option><option>&lt;=</option><option>&lt;</option></select></Field></div><div className="two-fields"><Field label="threshold · scaled integer"><input type="number" value={d.analysisSpec.threshold_scaled} onChange={e=>patchAnalysis("threshold_scaled",e.target.value)}/></Field><Field label="value field"><input value={d.analysisSpec.value_field||""} onChange={e=>patchAnalysis("value_field",e.target.value)} placeholder="value"/></Field></div>{(d.analysisSpec.profile==="TWO_GROUP_MEAN_DIFF"||d.analysisSpec.profile==="BINARY_RATE_DIFF")&&<><div className="three-fields"><Field label="group field"><input value={d.analysisSpec.group_field||""} onChange={e=>patchAnalysis("group_field",e.target.value)} placeholder="group"/></Field><Field label="group A"><input value={d.analysisSpec.group_a||""} onChange={e=>patchAnalysis("group_a",e.target.value)} placeholder="A"/></Field><Field label="group B"><input value={d.analysisSpec.group_b||""} onChange={e=>patchAnalysis("group_b",e.target.value)} placeholder="B"/></Field></div>{d.analysisSpec.profile==="BINARY_RATE_DIFF"&&<Field label="success field"><input value={d.analysisSpec.success_field||""} onChange={e=>patchAnalysis("success_field",e.target.value)} placeholder="success"/></Field>}</>}<div className="two-fields"><Field label="minimum scaled value"><input type="number" value={d.analysisSpec.min_value_scaled} onChange={e=>patchAnalysis("min_value_scaled",e.target.value)}/></Field><Field label="maximum scaled value"><input type="number" value={d.analysisSpec.max_value_scaled} onChange={e=>patchAnalysis("max_value_scaled",e.target.value)}/></Field></div>{analysisError(d.analysisSpec)&&<div className="error-leaf">{analysisError(d.analysisSpec)}</div>}</div></>}
 {step===2&&<><h3>Define the outcome law.</h3><p>Specify exactly what the evidence must show for REPLICATED versus FAILED TO REPLICATE. Protocol deviation and inconclusive outcomes remain separate.</p><Field label="registered outcome rule"><textarea value={d.outcomeRule} onChange={e=>setD(x=>({...x,outcomeRule:e.target.value}))} placeholder="REPLICATED when... FAILED TO REPLICATE when..."/></Field></>}
 {step===3&&<><h3>Set the evidence standard.</h3><p>Evidence is typed. The replication engine will not treat a generic list of URLs as sufficient by itself.</p><div className="two-fields"><Field label="required evidence kinds"><select multiple size={7} value={d.evidencePolicy.required_kinds} onChange={e=>setD(x=>({...x,evidencePolicy:{...x.evidencePolicy,required_kinds:selectedKinds(e.currentTarget)}}))}>{["DATASET","METHOD","ANALYSIS","RESULT_TABLE","PREREGISTRATION_REFERENCE","INDEPENDENT_OBSERVATION","SUPPLEMENT"].map(k=><option key={k} value={k}>{k}</option>)}</select></Field><div><Field label="minimum distinct origins"><input type="number" min="1" max="8" value={d.evidencePolicy.min_distinct_origins||2} onChange={e=>setD(x=>({...x,evidencePolicy:{...x.evidencePolicy,min_distinct_origins:Number(e.target.value)}}))}/></Field><Field label="allowed origins · optional"><textarea value={(d.evidencePolicy.allowed_origins||[]).join("\n")} onChange={e=>setD(x=>({...x,evidencePolicy:{...x.evidencePolicy,allowed_origins:e.target.value.split(/\n+/).map(v=>v.trim()).filter(Boolean)}}))} placeholder={'https://zenodo.org\nhttps://osf.io'}/></Field><Field label="required origins · optional"><textarea value={(d.evidencePolicy.required_origins||[]).join("\n")} onChange={e=>setD(x=>({...x,evidencePolicy:{...x.evidencePolicy,required_origins:e.target.value.split(/\n+/).map(v=>v.trim()).filter(Boolean)}}))} placeholder="Exact origins that must appear in every attempt."/></Field><Field label="policy note"><textarea value={d.evidencePolicy.notes||""} onChange={e=>setD(x=>({...x,evidencePolicy:{...x.evidencePolicy,notes:e.target.value}}))} placeholder="Any extra evidentiary constraints."/></Field></div></div></>}
 {step===4&&<><h3>Optional replication fund.</h3><p>Positive and negative valid replications receive the same fixed reward. Protocol deviations and inconclusive attempts do not receive a reward automatically.</p><div className="two-fields"><Field label="reward per valid attempt (GEN)"><input type="number" min="0" step="0.01" value={d.rewardGen} onChange={e=>setD(x=>({...x,rewardGen:e.target.value}))}/></Field><Field label="maximum rewarded attempts"><input type="number" min="0" max="100" value={d.maxRewardedAttempts} onChange={e=>setD(x=>({...x,maxRewardedAttempts:e.target.value}))}/></Field></div></>}
 {step===5&&<><h3>Freeze this preregistration.</h3><p>After registration, the claim, protocol, outcome rule, evidence policy and reward policy cannot be rewritten. The creator may only close the study to new replication attempts.</p><div className="margin-note"><b>{d.title}</b><p>{d.claim}</p><div className="micro">{d.field} · {d.studyKey}</div></div>{!w.address&&<div className="config-leaf">Connect a researcher identity to freeze the study.</div>}{tx&&<><Tx state={tx}/><div className="finality-actions"><button className="outline-action" onClick={check}>check finality</button>{tx.phase==="READY_TO_FINALIZE"&&<button className="ink-action" onClick={finalize}>finalize registration</button>}</div></>}</>}
 {err&&<div className="error-leaf">{err}</div>}<div className="registration-actions"><button className="outline-action" disabled={step===0} onClick={()=>setStep(x=>Math.max(0,x-1))}>back</button>{step<5?<button className="ink-action" disabled={!canNext} onClick={()=>setStep(x=>Math.min(5,x+1))}>continue</button>:<button className="ink-action" onClick={submit} disabled={!!tx&&["AWAITING_SIGNATURE","SUBMITTED","CONSENSUS_RUNNING"].includes(tx.phase)}>freeze registration</button>}</div></div></section>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="field-block"><label>{label}</label>{children}</div>}
function Tx({state}:{state:ResearchTxState}){return <div className="tx-trace"><strong>{state.phase.replaceAll("_"," ")}</strong><p>{state.message}</p>{state.txId&&<code>{state.txId}</code>}</div>}
