"use client";
import {useMemo,useState} from "react";
import {useResearcher} from "@/identity/researcher-session";
import {createStudy} from "@/contracts/study-registry";
import type {StudyDraft} from "@/research/study/study-model";
import {inspectTransaction,finalizeResearchTx,type ResearchTxState} from "@/consensus/write-pipeline";

const initial:StudyDraft={studyKey:"",title:"",field:"",claim:"",protocol:{population:"",procedure:"",measurement:"",analysis:"",window:""},outcomeRule:"",evidencePolicy:{required_kinds:["DATASET","METHOD","ANALYSIS","RESULT_TABLE"],min_distinct_origins:2,allowed_origins:[],required_origins:[],notes:""},rewardGen:"0",maxRewardedAttempts:"0"};
const steps=["claim","protocol","outcome","evidence","reward","freeze"];
export function RegisterStudy({onExit,onCreated}:{onExit:()=>void;onCreated:()=>void}){
 const w=useResearcher();const[d,setD]=useState(initial),[step,setStep]=useState(0),[err,setErr]=useState(""),[tx,setTx]=useState<ResearchTxState|null>(null);const p=d.protocol;
 const canNext=useMemo(()=>step===0?d.studyKey.length>=3&&d.title.length>=6&&d.field.length>=2&&d.claim.length>=20:step===1?Object.values(p).every(v=>String(v).trim().length>0):step===2?d.outcomeRule.length>=20:step===3?d.evidencePolicy.required_kinds.length>=2:step===4?Number(d.rewardGen)>=0&&Number(d.maxRewardedAttempts)>=0:true,[step,d,p]);
 const patchProtocol=(k:string,v:string)=>setD(x=>({...x,protocol:{...x.protocol,[k]:v}}));
 const selectedKinds=(el:HTMLSelectElement)=>Array.from(el.selectedOptions).map(o=>o.value);
 const submit=async()=>{setErr("");if(!w.address){setErr("Connect a researcher identity before freezing the study.");return}if(!w.chainOk){setErr("Switch your wallet to GenLayer Studionet 61999.");return}try{await createStudy(w.address,d,setTx)}catch(e:any){setErr(e?.message||"Study registration failed")}};
 const check=async()=>{if(!tx?.txId)return;try{const s=await inspectTransaction(w.address||undefined,tx.txId);setTx(s);if(s.phase==="FINALIZED")onCreated()}catch(e:any){setErr(e?.message||"Could not inspect registration finality")}};
 const finalize=async()=>{if(!w.address||!tx?.txId)return;try{await finalizeResearchTx(w.address,tx.txId);setTimeout(check,1200)}catch(e:any){setErr(e?.message||"Registration finalization failed")}};
 return <section className="registration-frame"><div className="registration-head"><div><div className="journal-kicker">preregistration desk</div><h2>Register a study</h2></div><button className="text-action" onClick={onExit}>return to atlas</button></div><div className="step-rail">{steps.map((s,i)=><div key={s} className={i<step?"done":i===step?"active":""}>{String(i+1).padStart(2,"0")} {s}</div>)}</div><div className="registration-sheet">{step===0&&<><h3>What claim is being tested?</h3><p>Write the claim precisely enough that another researcher can understand what the replication is meant to evaluate.</p><Field label="study key"><input value={d.studyKey} onChange={e=>setD(x=>({...x,studyKey:e.target.value.replace(/[^A-Za-z0-9_-]/g,"")}))} placeholder="sleep-recall-01"/></Field><Field label="title"><input value={d.title} onChange={e=>setD(x=>({...x,title:e.target.value}))} placeholder="Sleep duration and delayed recall"/></Field><Field label="field"><input value={d.field} onChange={e=>setD(x=>({...x,field:e.target.value}))} placeholder="Behavioural science"/></Field><Field label="registered claim"><textarea value={d.claim} onChange={e=>setD(x=>({...x,claim:e.target.value}))} placeholder="State the exact scientific claim to be tested."/></Field></>}
 {step===1&&<><h3>Freeze the method.</h3><p>The protocol becomes immutable once the registration transaction is finalized.</p>{(["population","procedure","measurement","analysis","window"] as const).map(k=><Field key={k} label={k}><textarea value={String(p[k])} onChange={e=>patchProtocol(k,e.target.value)} placeholder={`Describe the registered ${k}.`}/></Field>)}</>}
 {step===2&&<><h3>Define the outcome law.</h3><p>Specify exactly what the evidence must show for REPLICATED versus FAILED TO REPLICATE. Protocol deviation and inconclusive outcomes remain separate.</p><Field label="registered outcome rule"><textarea value={d.outcomeRule} onChange={e=>setD(x=>({...x,outcomeRule:e.target.value}))} placeholder="REPLICATED when... FAILED TO REPLICATE when..."/></Field></>}
 {step===3&&<><h3>Set the evidence standard.</h3><p>Evidence is typed. The replication engine will not treat a generic list of URLs as sufficient by itself.</p><div className="two-fields"><Field label="required evidence kinds"><select multiple size={7} value={d.evidencePolicy.required_kinds} onChange={e=>setD(x=>({...x,evidencePolicy:{...x.evidencePolicy,required_kinds:selectedKinds(e.currentTarget)}}))}>{["DATASET","METHOD","ANALYSIS","RESULT_TABLE","PREREGISTRATION_REFERENCE","INDEPENDENT_OBSERVATION","SUPPLEMENT"].map(k=><option key={k} value={k}>{k}</option>)}</select></Field><div><Field label="minimum distinct origins"><input type="number" min="1" max="8" value={d.evidencePolicy.min_distinct_origins||2} onChange={e=>setD(x=>({...x,evidencePolicy:{...x.evidencePolicy,min_distinct_origins:Number(e.target.value)}}))}/></Field><Field label="allowed origins · optional"><textarea value={(d.evidencePolicy.allowed_origins||[]).join("\n")} onChange={e=>setD(x=>({...x,evidencePolicy:{...x.evidencePolicy,allowed_origins:e.target.value.split(/\n+/).map(v=>v.trim()).filter(Boolean)}}))} placeholder={'https://zenodo.org\nhttps://osf.io'}/></Field><Field label="required origins · optional"><textarea value={(d.evidencePolicy.required_origins||[]).join("\n")} onChange={e=>setD(x=>({...x,evidencePolicy:{...x.evidencePolicy,required_origins:e.target.value.split(/\n+/).map(v=>v.trim()).filter(Boolean)}}))} placeholder="Exact origins that must appear in every attempt."/></Field><Field label="policy note"><textarea value={d.evidencePolicy.notes||""} onChange={e=>setD(x=>({...x,evidencePolicy:{...x.evidencePolicy,notes:e.target.value}}))} placeholder="Any extra evidentiary constraints."/></Field></div></div></>}
 {step===4&&<><h3>Optional replication fund.</h3><p>Positive and negative valid replications receive the same fixed reward. Protocol deviations and inconclusive attempts do not receive a reward automatically.</p><div className="two-fields"><Field label="reward per valid attempt (GEN)"><input type="number" min="0" step="0.01" value={d.rewardGen} onChange={e=>setD(x=>({...x,rewardGen:e.target.value}))}/></Field><Field label="maximum rewarded attempts"><input type="number" min="0" max="100" value={d.maxRewardedAttempts} onChange={e=>setD(x=>({...x,maxRewardedAttempts:e.target.value}))}/></Field></div></>}
 {step===5&&<><h3>Freeze this preregistration.</h3><p>After registration, the claim, protocol, outcome rule, evidence policy and reward policy cannot be rewritten. The creator may only close the study to new replication attempts.</p><div className="margin-note"><b>{d.title}</b><p>{d.claim}</p><div className="micro">{d.field} · {d.studyKey}</div></div>{!w.address&&<div className="config-leaf">Connect a researcher identity to freeze the study.</div>}{tx&&<><Tx state={tx}/><div className="finality-actions"><button className="outline-action" onClick={check}>check finality</button>{tx.phase==="READY_TO_FINALIZE"&&<button className="ink-action" onClick={finalize}>finalize registration</button>}</div></>}</>}
 {err&&<div className="error-leaf">{err}</div>}<div className="registration-actions"><button className="outline-action" disabled={step===0} onClick={()=>setStep(x=>Math.max(0,x-1))}>back</button>{step<5?<button className="ink-action" disabled={!canNext} onClick={()=>setStep(x=>Math.min(5,x+1))}>continue</button>:<button className="ink-action" onClick={submit} disabled={!!tx&&["AWAITING_SIGNATURE","SUBMITTED","CONSENSUS_RUNNING"].includes(tx.phase)}>freeze registration</button>}</div></div></section>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="field-block"><label>{label}</label>{children}</div>}
function Tx({state}:{state:ResearchTxState}){return <div className="tx-trace"><strong>{state.phase.replaceAll("_"," ")}</strong><p>{state.message}</p>{state.txId&&<code>{state.txId}</code>}</div>}
